apiVersion: v1
kind: Service
metadata:
  name: {{ include "ark-server.fullname" . }}
  labels:
    {{- include "ark-server.labels" . | nindent 4 }}
spec:
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  type: {{ .Values.service.type }}
  ports:
    - port: 27015
      targetPort: query
      protocol: UDP
      name: query
    - port: 7777
      targetPort: client
      protocol: UDP
      name: client
    - port: 7778
      targetPort: raw
      protocol: UDP
      name: raw
    - port: 27020
      targetPort: rcon
      protocol: TCP
      name: rcon
  selector:
    {{- include "ark-server.selectorLabels" . | nindent 4 }}
